# Generated by Django 4.1.3 on 2022-11-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(default="example@email.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(default="12", max_length=50),
            preserve_default=False,
        ),
    ]
