# Generated by Django 3.2.16 on 2022-12-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_email_alter_customer_license_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('SHQIPËRISË', 'Shqipëria'), ('KOSOVËS', 'Kosovës'), ('ITALISË', 'Italisë'), ('SHBA', 'Shba')], default='ITALISË', max_length=10),
        ),
    ]
