# Generated by Django 3.2.16 on 2023-01-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_customer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Albania', 'Shqipëria'), ('Kosovo', 'Kosovës'), ('Italy', 'Italisë'), ('USA', 'Shba')], default='ITALISË', max_length=10),
        ),
    ]
