# Generated by Django 3.2.16 on 2023-04-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_customer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('Albania', 'Shqipëria'), ('Kosovo', 'Kosovës'), ('Italy', 'Italisë'), ('USA', 'Shba'), ('Bulgaria', 'Bullgari'), ('Turkey', 'Turqi')], default='Italisë', max_length=10),
        ),
    ]
