# Generated by Django 3.2.16 on 2022-11-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_alter_reservation_pickup_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="final_price",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=5),
            preserve_default=False,
        ),
    ]
