# Generated by Django 3.2.16 on 2022-11-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_reservation_final_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='final_price',
        ),
    ]
