# Generated by Django 3.2.16 on 2023-01-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_expenses_expense_sum'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='comments',
            field=models.CharField(default='1', max_length=256),
            preserve_default=False,
        ),
    ]
