# Generated by Django 3.2.16 on 2022-11-21 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cars", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cars",
            new_name="Car",
        ),
    ]
